#!/usr/bin/env python
import os
import pwd
import grp
import sys
import signal
import base64
import ldap
import argparse
from http.server import HTTPServer, BaseHTTPRequestHandler
import pickle
from data_file_descriptor import AccessType, DataFileStorage

# -----------------------------------------------------------------------------
# Requests are processed in separate thread
import threading
from socketserver import ThreadingMixIn
class AuthHTTPServer(ThreadingMixIn, HTTPServer):
    pass
# -----------------------------------------------------------------------------
# Requests are processed in separate process
# from SocketServer import ForkingMixIn
# class AuthHTTPServer(ForkingMixIn, HTTPServer):
#    pass
# -----------------------------------------------------------------------------
# Requests are processed with UNIX sockets
# Listen = "/tmp/auth.sock"
# import threading
# from SocketServer import ThreadingUnixStreamServer
# class AuthHTTPServer(ThreadingUnixStreamServer, HTTPServer):
#    pass
# -----------------------------------------------------------------------------
conf = {}



def read_conf(fname):
    """read file in pam_ldap format"""
    global conf
    opts = ['host', 'base', 'binddn', 'bindpw', 'ssl', 'filedescrpth']
    try:
        with open(fname) as f:
            for line in f:
                data = line.strip().split()
                if len(data) > 1 and data[0] in opts:
                    conf[data[0]] = ' '.join(data[1:])
    except:
        print("Unable to read {} as uid {}: {}".format(fname, os.getuid(), sys.exc_info()))
        sys.exit(1)

    for o in opts[:4]:
        if o not in conf:
            print("Mandatory parameter '{}' was not found in config file {}!".format(o, fname))
            sys.exit(1)


def drop_privileges(uid_name='nobody', gid_name='nogroup'):
    if os.getuid() != 0:
        return
    uid = pwd.getpwnam(uid_name).pw_uid
    gid = grp.getgrnam(gid_name).gr_gid
    os.setgroups([])
    os.setgid(gid)
    os.setuid(uid)


def exit_handler(signal, frame):
    sys.exit(0)


def check_auth(user, passwd, allowusr, allowgr):
    """check password and group membership"""
    proto = 'ldap://' if conf['ssl'] != 'on' else 'ldaps://'
    ldap_connection = None
    for host in conf['host'].split():
        try:
            ldap_connection = ldap.initialize(proto + host)
            ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)
            ldap_connection.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_ALLOW)
            ldap_connection.set_option(ldap.OPT_REFERRALS, 0)  # MS AD
            ldap_connection.set_option(ldap.OPT_NETWORK_TIMEOUT, 3)
            ldap_connection.simple_bind_s(conf['binddn'], conf['bindpw'])
            data = ldap_connection.search_s(base=conf['base'], scope=ldap.SCOPE_SUBTREE,
                                            filterstr='(&(objectClass=person)(uid=' + user + '))')
            if data:
                dn = data[0][0]
                data = data[0][1]
                # check password
                try:
                    ldap_connection.simple_bind_s(dn, passwd)
                except ldap.INVALID_CREDENTIALS:
                    return False
                # check allowed users
                if bool(allowusr) and str(data['uniqueIdentifier'][0], 'utf-8') in [x.strip() for x in allowusr.split(',')]:
                    return True
                # check allowed groups
                if bool(allowgr):
                    groups_set = set([str(d, 'utf-8') for d in data['memberOf']])
                    allowgr_set = set([x.strip() for x in allowgr.split(',')])
                    if bool(groups_set & allowgr_set):
                        return True
                # user found but not in allowed
                return False if bool(allowusr) or bool(allowgr) else True
        except (ldap.CONNECT_ERROR, ldap.SERVER_DOWN):
            pass  # try next server
        finally:
            if ldap_connection:
                ldap_connection.unbind()
    return False


class LDAPAuthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        try:
            allowusr = self.headers.get('X-Ldap-Allowed-Usr')
            allowgr = self.headers.get('X-Ldap-Allowed-Grp')
            document_uri = self.headers.get('X-Ldap-Document-Uri')
            auth_header = self.headers.get('Authorization')
            document_uri = self.headers.get('X-Ldap-Document-Uri')
            document_uri_alternate = self.path
            file_path = ''
            document_mode = False
            if document_uri in files_descriptor.storage:
                document_mode = True
                file_path = files_descriptor.get(document_uri).file_path
                file_path_alternate = files_descriptor.get(document_uri_alternate).file_path
                allowusr = ','.join(files_descriptor.get(document_uri).allowed_users)
                allowgr = ','.join(files_descriptor.get(document_uri).allowed_groups)
                if files_descriptor.get(document_uri).access_type == AccessType.free:
                    allowusr = '_anybody'
                if files_descriptor.get(document_uri).access_type == AccessType.public:
                    allowusr = ''
                    allowgr = ''
                print(file_path, allowusr, allowgr)
                
            if allowusr == '_anybody':
                self.send_response(200)
                if document_mode :
                    self.send_header('X-File-Path', file_path)
                    self.send_header('X-File-Path', file_path_alternate)
                return
            if auth_header and auth_header.lower().startswith('basic '):
                user, passwd = str(base64.b64decode(auth_header[6:]), 'utf-8').split(':', 1)
                if check_auth(user, passwd, allowusr, allowgr):
                    self.send_response(200)
                    if document_mode:
                        self.send_header('X-File-Path', file_path)
                        self.send_header('X-File-Path', file_path_alternate)
                    return
            self.send_response(401)
            realm = self.headers.get('X-Ldap-Realm')
            if not realm:
                realm = 'Authorization required'
            self.send_header('WWW-Authenticate', 'Basic realm="{}"'.format(realm))
            self.send_header('Cache-Control', 'no-cache')
        except:
            self.send_response(500)
            self.send_header('X-Error-Message', sys.exc_info()[1])
        finally:
            self.end_headers()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="""Simple Nginx LDAP authentication helper.""")
    parser.add_argument('--host', default="localhost", help="host to bind (Default: localhost)")
    parser.add_argument('-p', '--port', type=int, default=8888, help="port to bind (Default: 8888)")
    parser.add_argument('-c', '--config', default='/etc/pam_ldap.conf', help="config with LDAP creds (Default: /etc/pam_ldap.conf)")
    args = parser.parse_args()

    read_conf(args.config)

    drop_privileges()
    signal.signal(signal.SIGINT, exit_handler)

    files_descriptor = DataFileStorage()
    files_descriptor.load(conf['filedescrpth'])

    server = AuthHTTPServer((args.host, args.port), LDAPAuthHandler)
    server.serve_forever()
